name: note
description: "FKRNY"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.16
  dartz: ^0.10.1
  path: ^1.9.0
  modal_progress_hud_nsn: ^0.5.1
  get_it: ^8.0.3
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
   - family: Nunito
     fonts:
       - asset: assets/fonts/Nunito-Bold.ttf
         weight: 700
       - asset: assets/fonts/Nunito-Regular.ttf
         weight: 400
       - asset: assets/fonts/Nunito-SemiBold.ttf
         weight: 600
       - asset: assets/fonts/Nunito-Medium.ttf
         weight: 500


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
  assets:
    - assets/images/
    - lib/core/function_helper/

